<a href="https://colab.research.google.com/github/anyuanay/INFO212/blob/main/INFO212_Week4_Lecture2_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INFO 212: Data Science Programming 1
___

## Week 4: Lecture 2: Numpy and Pandas
---

**Agenda:**
- Review on linear algebra and numpy
- Introduction to Pandas
 * What is Pandas?
 * Importance in data analysis
- Exploring DataFrame Structure
 * df.shape: Dimensions of DataFrame
 * df.describe(): Descriptive statistics of DataFrame
- Manipulating DataFrames
 * df.reindex(newIndex): Adjusting data to new indices
 * df.drop(columns, axis): Dropping columns from DataFrame
- DataFrame Indexing
 * df.iloc[]: Integer-location based indexing
 * df.loc[]: Label-based indexing
- Function Application on DataFrames
 * df.apply(f): Applying functions to DataFrame
- Sorting in DataFrames
 * df.sort_values(by): Sorting rows by column values
 * df.sort_index(axis): Sorting by DataFrame index
- Unique Values and Counts
 * df.Pclass.unique(): Extracting unique values from a column
 * df.Pclass.value_counts(): Counting unique value occurrences
- Read a CSV file as a DataFrame:
 * pd.read_csv()
---

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Linear Algebra

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [6]:
# dot product of two arrays
res = 0
for i in np.arange(a.shape[0]):
    res = res + a[i] * b[i]

res

np.int64(32)

In [5]:
a.dot(b)

np.int64(32)

In [7]:
a * b

array([ 4, 10, 18])

# Matrix Multiplication

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 1]])
A.shape, B.shape

((2, 3), (3, 2))

In [11]:
# Get dimensions
rows_A, cols_A = A.shape
rows_B, cols_B = B.shape

In [15]:
# Initialize result matrix C with zeros (shape: rows_A x cols_B)
C = np.zeros((rows_A, cols_B))

# Matrix multiplication using nested loops
for i in np.arange(rows_A):  # Iterate over rows of A
    for j in np.arange(cols_B):  # Iterate over columns of B
        C[i, j] = A[i].dot(B[:, j])

C

array([[ 4.,  5.],
       [10., 11.]])

In [9]:
A @ B

array([[ 4,  5],
       [10, 11]])

In [10]:
A * B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

# Aggregation along axis

In [16]:
X = np.array([[3, 1, 0], [1, 1, 0], [1, 0, 2]])
X

array([[3, 1, 0],
       [1, 1, 0],
       [1, 0, 2]])

In [18]:
X.mean(0), X.mean(1)

(array([1.66666667, 0.66666667, 0.66666667]),
 array([1.33333333, 0.66666667, 1.        ]))

In [22]:
norms = np.linalg.norm(X, axis = 1)
norms

array([3.16227766, 1.41421356, 2.23606798])

In [34]:
U = X / norms.reshape(-1, 1)
U

array([[0.9486833 , 0.31622777, 0.        ],
       [0.70710678, 0.70710678, 0.        ],
       [0.4472136 , 0.        , 0.89442719]])

In [35]:
np.linalg.norm(U, axis=1)

array([1., 1., 1.])

In [37]:
U @ U.T

array([[1.        , 0.89442719, 0.42426407],
       [0.89442719, 1.        , 0.31622777],
       [0.42426407, 0.31622777, 1.        ]])

# Numpy Array Indexing and Slicing
An numpy array can be subsetted based on positions or conditions.

For example, given the 2x2 numpy array:
```
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7]]),
```

The indexing operation `arr[0, 1]`  extracts the element at row 0 and column 1.

The indexing operation
`arr[:, 1:3]` extracts all rows (indicated by `:`) for columns 1 to 3 (not including column 3).     

The indexing operation `arr[1:, 1:2]` extracts the rows from 1 to the end of rows and column 1.

The indexing operation `arr[arr > 3]` extracts the values that are greater than 3.


## Exercise:
- What does `arr[[True, False]]` extract?
- What does `arr[:, [False, False, True, False]]` extract?

# Retrieval Practice

# What is Pandas?
- Pandas: High-performance, easy-to-use data structures and data analysis tools.
- Fundamental for data manipulation in Python.
- Contains data structures and data manipulation tools designed to make data cleaning and analysis fast and easy in Python.
- Often used togeter with numerical computing tools like NumPy and SciPy, analytical libraries like statsmodels and scikit-learn, and data visualization libraries like matplotlib.
- Adopts significant parts of NumPy’s idiomatic style of array-based computing, especially array-based functions and a preference for data processing without 'for' loops.


# Series and DataFrame

## Series
- A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its index.

![](https://i.imgur.com/4hGYKrX.png)

Key Features:
- Homogeneous data
- Size immutable
- Data values can be mutable
- Axis labels (can be of any type: string, integer, date-time, etc.)


## Exercise:
Creating a Series from an array:
```
s1 = pd.Series([1, 2, 3, 4, 5])
```
What are the index and values?



## Exercise:
Create a series from a dictionary:
```
data = {'a': 0., 'b': 1., 'c': 2.}
s2 = pd.Series(data)
```

What are the index and values?


## Exercise:
Create a series from a scalar:
```
s3 = pd.Series(5, index=[0, 1, 2, 3])
```

What are the index and values?

### Accessing Data in a Series:

- Using position:
```
s1[0]  # Output: 1
```

- Using the label/index:
```
s2['b']  # Output: 1.0
```

## DataFrame

- A DataFrame represents a rectangular table of data and contains an ordered collection
of columns, each of which can be a different value type (numeric, string,
boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dict of Series all sharing the same index.

![](https://i.imgur.com/3MUvN7R.png)

Key Features:
- Heterogeneous data (can store columns of different types)
Size mutable
- Data can be set and fetched using row labels and column names



## Exercise:
Creating a DataFrame from a dictionary of Series or dictionaries:
```
data = {'Name': pd.Series(['Alice', 'Bob', 'Chris']),
        'Age': pd.Series([25, 26, 24])}
df1 = pd.DataFrame(data)
```

What are the index and column labels of the dataframe?

## Exercise:
Create a DataFrame from a list of dictionaries:
```
data = [{'Name': 'Alice', 'Age': 25}, {'Name': 'Bob', 'Age': 26}]
df2 = pd.DataFrame(data)
```

What are the index and column labels of the dataframe?

## Exercise:
Create a DataFrame from an array or list:
```
data = [['Alex', 10], ['Bob', 15], ['Charlie', 14]]
df3 = pd.DataFrame(data, columns=['Name', 'Age'])
```

What are the index and column labels of the dataframe?

## Series and DataFrame

![](https://i.imgur.com/4QEW9Dd.png)

### Each column or row of a DataFrame is a Series
![](https://i.imgur.com/rHJsq6F.png)

# Retrieval Practice