<a href="https://colab.research.google.com/github/anyuanay/INFO212/blob/main/INFO212_Week3_Lecture1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INFO 212: Data Science Programming 1
___

## Week 3: Lecture 1: Numpy: Arrays and Vectorized Computation
___

**Agenda:**
- Introduction to NumPy
 * What is NumPy?
 * Why use NumPy?
- Getting Started with NumPy
 * Installation and Setup
 * Creating Arrays
- Diving Deep: Array Basics
 * Array Properties
 * Reshaping and Flattening
 * Basic Operations
- Advanced Array Operations
 * Broadcasting
 * Indexing and Slicing
 * Fancy Indexing
 * File I/O


# What is Numpy?
- A fundamental library for numerical computing in Python.
- Main feature: n-dimensional array object.
![](https://i.imgur.com/dKrKVKk.jpg)

In [1]:
import numpy as np

# Broadcasting
Broadcasting defines how NumPy handles operations on arrays of different shapes. It extends smaller arrays to match the shape of larger ones.
```
a = np.array([1, 2, 3])
b = 2
a * b  # array([2, 4, 6])
```

## Exercise:
Can you add a 3x4 array and a 1x4 array? Can you add a 3x4 array and a 2x4 array? Can you add a 3x1 array and a 2x4 array? Can you add a 2x1 array and a 2x4 array? Can you add a 3x4 array and a 3x1 array? Explain what is broadcasted in each permissiable operation.

# Indexing and Slicing
Accessing parts of the array based on conditions or positions.
```
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]      # 2
arr[:, 1:3]    # array([[2, 3], [5, 6]])
```

$m\times n$ array's index starts from 0, 0 to m, n.
![](https://i.imgur.com/2zwzXCw.png)

# Fancy Indexing
We also can use integer arrays or boolean values for array indexing.
```
arr = np.array([10, 20, 30, 40, 50])
idx = np.array([1, 3])
arr[idx]  # array([20, 40])
```

## Exercise:
Given an array. Extract all the items that have an odd index.

### Boolean Indexing
Given an arry, how to get values that meet a condition?

In [3]:
arr = np.random.random((2, 3))
arr

array([[0.57902037, 0.87095791, 0.14237126],
       [0.45886238, 0.80434524, 0.09111036]])

In [6]:
arr[arr > 0.5]

array([0.57902037, 0.87095791, 0.80434524])

### Methods for Boolean Arrays
Boolean values are coerced to 1 (True) and 0 (False). Thus,
sum is often used as a means of counting True values in a boolean array.

How many values are greater than 0.5 in each row?

In [8]:
np.sum(arr > 0.5, axis=1)

array([2, 1])

## File Input and Output with Arrays
np.load() and np.save() are the two workhorse functions for efficiently loading and saving
array data on disk. Arrays are saved by default in an uncompressed raw binary
format with file extension .npy.
- Download the zipped file "inflammation-data.zip" and unzip it in a folder in your Drive. You should see a directory "inflammation-data" containing data files.
- Mount Drive.

### Load a file to a numpy array

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
afile_path = "/content/drive/MyDrive/Colab Notebooks/courses/INFO212/INFO212_Fall2026/data/inflammation-data/inflammation-01.csv"

In [12]:
arr = np.loadtxt(afile_path, delimiter=",")

In [14]:
arr.shape

(60, 40)

### Save a numpy arrary to disk

In [16]:
np.save('inflammation01.npy', arr)

```
data_load = np.load('datasets/inflamation.npy')
```

In [18]:
data_load = np.load('inflammation01.npy')

In [20]:
data_load == arr

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])